
macro(setup)

	string(TOUPPER ${PROJECT_NAME} PROJECT_NAME_UPPER)
	string(TOLOWER ${PROJECT_NAME} PROJECT_NAME_LOWER)

	set(FULL_PROJECT_NAME ${PROJECT_NAME})

	get_directory_property(HAS_PARENT PARENT_DIRECTORY)

	if(HAS_PARENT)

		set(FULL_PROJECT_NAME ${CMAKE_PROJECT_NAME}-${PROJECT_NAME})

		string(TOUPPER ${CMAKE_PROJECT_NAME} PARENT_PROJECT_NAME_UPPER)
		string(TOLOWER ${CMAKE_PROJECT_NAME} PARENT_PROJECT_NAME_LOWER)

	endif()

	string(TOUPPER ${FULL_PROJECT_NAME} FULL_PROJECT_NAME_UPPER)
	string(REPLACE "-" "_" FULL_PROJECT_NAME_UPPER ${FULL_PROJECT_NAME_UPPER})

	set(${FULL_PROJECT_NAME_UPPER}_VERSION ${PROJECT_VERSION})
	set(${FULL_PROJECT_NAME_UPPER}_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
	set(${FULL_PROJECT_NAME_UPPER}_VERSION_MINOR ${PROJECT_VERSION_MINOR})
	set(${FULL_PROJECT_NAME_UPPER}_VERSION_PATCH ${PROJECT_VERSION_PATCH})

	message(STATUS "${FULL_PROJECT_NAME} version: ${${FULL_PROJECT_NAME_UPPER}_VERSION_MAJOR}.${${FULL_PROJECT_NAME_UPPER}_VERSION_MINOR}.${${FULL_PROJECT_NAME_UPPER}_VERSION_PATCH}")

endmacro()
